<?php

declare(strict_types=1);

namespace StreameryForms\Assets;

defined('ABSPATH') || exit;

/**
 * Class Strings
 *
 * Collects and provides all translatable strings for JavaScript.
 *
 * @package StreameryForms\Assets
 */
class Strings
{

	/**
	 * Get all translatable strings as an array.
	 *
	 * @return array Array of translated strings.
	 */
	public static function get_strings(): array
	{
		return array(
			// Common
			'loading' => __('Loading...', 'streamery-forms'),
			'error' => __('Error', 'streamery-forms'),
			'errorOccurred' => __('An error occurred', 'streamery-forms'),
			'save' => __('Save', 'streamery-forms'),
			'cancel' => __('Cancel', 'streamery-forms'),
			'delete' => __('Delete', 'streamery-forms'),
			'edit' => __('Edit', 'streamery-forms'),
			'create' => __('Create', 'streamery-forms'),
			'update' => __('Update', 'streamery-forms'),
			'close' => __('Close', 'streamery-forms'),
			'yes' => __('Yes', 'streamery-forms'),
			'no' => __('No', 'streamery-forms'),
			'copied' => __('Copied', 'streamery-forms'),
			'copy' => __('Copy', 'streamery-forms'),
			'copyToClipboard' => __('Copy to clipboard', 'streamery-forms'),
			'copiedExclamation' => __('Copied!', 'streamery-forms'),

			// Login Page
			'login' => __('Login', 'streamery-forms'),
			'loginDescription' => __('Enter your email below to login to your account', 'streamery-forms'),
			'email' => __('Email', 'streamery-forms'),
			'password' => __('Password', 'streamery-forms'),
			'forgotPassword' => __('Forgot your password?', 'streamery-forms'),
			'loginWithGoogle' => __('Login with Google', 'streamery-forms'),
			'dontHaveAccount' => __("Don't have an account?", 'streamery-forms'),
			'signUp' => __('Sign up', 'streamery-forms'),

			// Error Page
			'oops' => __('Oops!', 'streamery-forms'),
			'unexpectedError' => __('Sorry, an unexpected error has occurred.', 'streamery-forms'),

			// Welcome Page
			'addFirstMailProvider' => __('Add your first Mail Provider', 'streamery-forms'),
			'addFirstMailProviderDesc' => __('Configure an email provider to receive form submissions via email.', 'streamery-forms'),
			'createFirstMailbox' => __('Create your first Mailbox', 'streamery-forms'),
			'createFirstMailboxDesc' => __('Organize form submissions into mailboxes for better management.', 'streamery-forms'),
			'addFirstLabel' => __('Add your first Label', 'streamery-forms'),
			'addFirstLabelDesc' => __('Create labels to categorize and organize your form entries.', 'streamery-forms'),
			'createFirstForm' => __('Create your first Form', 'streamery-forms'),
			'createFirstFormDesc' => __('Build a form in the block editor and start collecting submissions.', 'streamery-forms'),
			'buildYourFirstForm' => __('Build Your first Form', 'streamery-forms'),
			'createFirstFormDescription' => __('Create your first form in the block editor', 'streamery-forms'),
			'welcomeToStreameryForms' => __('Welcome to Streamery Forms!', 'streamery-forms'),
			'loadingChecklist' => __('Loading checklist...', 'streamery-forms'),
			'view' => __('View', 'streamery-forms'),
			'setup' => __('Setup', 'streamery-forms'),

			// Inbox Page
			'inbox' => __('Inbox', 'streamery-forms'),
			'autoRefresh' => __('Auto-refresh', 'streamery-forms'),
			'refresh' => __('Refresh', 'streamery-forms'),
			'autoRefreshDescription' => __('Automatically refresh entries every 5 seconds', 'streamery-forms'),
			'all' => __('All', 'streamery-forms'),
			'unread' => __('Unread', 'streamery-forms'),
			'read' => __('Read', 'streamery-forms'),
			'starred' => __('Starred', 'streamery-forms'),
			'unstarred' => __('Unstarred', 'streamery-forms'),
			'important' => __('Important', 'streamery-forms'),
			'followUp' => __('Follow Up', 'streamery-forms'),

			// Forms (posts with embedded forms)
			'forms' => __('Forms', 'streamery-forms'),
			'formsOnSite' => __('Forms', 'streamery-forms'),
			'noFormsOnSite' => __('No posts with embedded forms found.', 'streamery-forms'),
			'formId' => __('Form ID', 'streamery-forms'),
			'postTitle' => __('Title', 'streamery-forms'),
			'mailbox' => __('Mailbox', 'streamery-forms'),
			'fieldsCount' => __('Fields', 'streamery-forms'),
			'untitled' => __('Untitled', 'streamery-forms'),
			'patternUsedIn' => __('Pattern used in', 'streamery-forms'),

			// Settings - General
			'licenseKey' => __('License Key', 'streamery-forms'),
			'enterLicenseKey' => __('Enter your license key', 'streamery-forms'),
			'licenseKeyDescription' => __('Enter your Streamery Forms license key to unlock premium features.', 'streamery-forms'),
			'settingsSaved' => __('Settings saved', 'streamery-forms'),
			'settingsSavedDescription' => __('Your general settings have been updated successfully.', 'streamery-forms'),
			'saveChanges' => __('Save changes', 'streamery-forms'),
			'licenseKeyRequired' => __('License key is required.', 'streamery-forms'),

			// Settings - Providers
			'providers' => __('Providers', 'streamery-forms'),
			'manageProviders' => __('Manage your form submission providers.', 'streamery-forms'),
			'addProvider' => __('Add Provider', 'streamery-forms'),
			'more' => __('More', 'streamery-forms'),
			'moreProviders' => __('More', 'streamery-forms'),
			'less' => __('Less', 'streamery-forms'),
			'comingSoon' => __('Coming Soon', 'streamery-forms'),
			'addProviderFromType' => __('Add Provider', 'streamery-forms'),
			'searchProvider' => __('Search providers...', 'streamery-forms'),
			'createProvider' => __('Create Provider', 'streamery-forms'),
			'editProvider' => __('Edit Provider', 'streamery-forms'),
			'providerCreated' => __('Provider created', 'streamery-forms'),
			'providerCreatedDesc' => __('The provider has been created successfully.', 'streamery-forms'),
			'providerUpdated' => __('Provider updated', 'streamery-forms'),
			'preview' => __('Preview', 'streamery-forms'),
			'emailPreview' => __('Email Preview', 'streamery-forms'),
			'emailPreviewDescription' => __('Preview how your email template will look. Placeholders are highlighted in yellow.', 'streamery-forms'),
			'debugMode' => __('Debug Mode', 'streamery-forms'),
			'debugModeDescription' => __('Enable debug mode to see detailed information about form submissions in the frontend. Only visible to logged-in users.', 'streamery-forms'),
			'debugModeEnabled' => __('Debug mode has been enabled.', 'streamery-forms'),
			'debugModeDisabled' => __('Debug mode has been disabled.', 'streamery-forms'),
			'skipSetup' => __('Skip Setup', 'streamery-forms'),
			'letsGetYouStarted' => __('Let\'s get you started!', 'streamery-forms'),
			'showCharts' => __('Show Charts', 'streamery-forms'),
			'emptyTrash' => __('Empty Trash', 'streamery-forms'),
			'emptyTrashConfirmation' => __('Are you sure you want to permanently delete all entries in trash? This action cannot be undone.', 'streamery-forms'),
			'trashEmptied' => __('Trash emptied', 'streamery-forms'),
			'trashEmptiedDescription' => __('All entries in trash have been permanently deleted.', 'streamery-forms'),
			'emptying' => __('Emptying...', 'streamery-forms'),
			'selected' => __('selected', 'streamery-forms'),
			'selectedPlural' => __('selected', 'streamery-forms'),
			'selectAll' => __('Select All', 'streamery-forms'),
			'addLabel' => __('Add Label', 'streamery-forms'),
			'moveToArchive' => __('Move to Archive', 'streamery-forms'),
			'entriesDeleted' => __('Entries moved to Trash', 'streamery-forms'),
			'entriesDeletedDescription' => __('Selected entries have been moved to trash.', 'streamery-forms'),
			'entriesMoved' => __('Entries moved', 'streamery-forms'),
			'entriesMovedDescription' => __('Selected entries have been moved.', 'streamery-forms'),
			'entryMoved' => __('Entry moved', 'streamery-forms'),
			'entryMovedDescription' => __('Entry has been moved successfully.', 'streamery-forms'),
			'labelAdded' => __('Label added', 'streamery-forms'),
			'labelAddedDescription' => __('Label has been added to the entry.', 'streamery-forms'),
			'markAsRead' => __('Mark as Read', 'streamery-forms'),
			'markAsUnread' => __('Mark as Unread', 'streamery-forms'),
			'moveToTrash' => __('Move to Trash', 'streamery-forms'),
			'moveTo' => __('Move to', 'streamery-forms'),
			'moveToMailbox' => __('Move to Mailbox', 'streamery-forms'),
			'entryMovedToMailbox' => __('Entry moved to Mailbox', 'streamery-forms'),
			'entryUpdated' => __('Entry updated', 'streamery-forms'),
			'entryMarkedAsRead' => __('Entry has been marked as read.', 'streamery-forms'),
			'entryMarkedAsUnread' => __('Entry has been marked as unread.', 'streamery-forms'),
			'entryDeleted' => __('Entry moved to Trash', 'streamery-forms'),
			'entryDeletedDescription' => __('Entry has been moved to trash successfully.', 'streamery-forms'),
			'providerUpdatedDesc' => __('The provider has been updated successfully.', 'streamery-forms'),
			'providerDeleted' => __('Provider deleted', 'streamery-forms'),
			'providerDeletedDesc' => __('The provider has been deleted successfully.', 'streamery-forms'),
			'confirmDeleteProvider' => __('Are you sure you want to delete this provider?', 'streamery-forms'),
			'loadingProviders' => __('Loading providers...', 'streamery-forms'),
			'errorProviders' => __('Error:', 'streamery-forms'),
			'noProvidersFound' => __('No providers found. Create your first provider to get started.', 'streamery-forms'),
			'providerType' => __('Provider Type', 'streamery-forms'),
			'active' => __('Active', 'streamery-forms'),
			'inactive' => __('Inactive', 'streamery-forms'),
			'created' => __('Created', 'streamery-forms'),

			// Settings - Mailboxes
			'mailboxes' => __('Mailboxes', 'streamery-forms'),
			'manageMailboxes' => __('Manage your mailboxes for form submissions.', 'streamery-forms'),
			'addMailbox' => __('Add Mailbox', 'streamery-forms'),
			'createMailbox' => __('Create Mailbox', 'streamery-forms'),
			'editMailbox' => __('Edit Mailbox', 'streamery-forms'),
			'mailboxCreated' => __('Mailbox created', 'streamery-forms'),
			'mailboxCreatedDesc' => __('The mailbox has been created successfully.', 'streamery-forms'),
			'mailboxUpdated' => __('Mailbox updated', 'streamery-forms'),
			'mailboxUpdatedDesc' => __('The mailbox has been updated successfully.', 'streamery-forms'),
			'mailboxDeleted' => __('Mailbox deleted', 'streamery-forms'),
			'mailboxDeletedDesc' => __('The mailbox has been deleted successfully.', 'streamery-forms'),
			'confirmDeleteMailbox' => __('Are you sure you want to delete this mailbox?', 'streamery-forms'),
			'cannotDeleteDefaultMailbox' => __('Cannot delete default mailbox', 'streamery-forms'),
			'cannotDeleteDefaultMailboxDesc' => __('Please set another mailbox as default before deleting this one.', 'streamery-forms'),
			'loadingMailboxes' => __('Loading mailboxes...', 'streamery-forms'),
			'errorMailboxes' => __('Error:', 'streamery-forms'),
			'noMailboxesFound' => __('No mailboxes found. Create your first mailbox to get started.', 'streamery-forms'),
			'title' => __('Title', 'streamery-forms'),
			'titleRequired' => __('Title is required', 'streamery-forms'),
			'myMailbox' => __('My Mailbox', 'streamery-forms'),
			'mailboxTitleDescription' => __('A descriptive name for this mailbox.', 'streamery-forms'),
			'defaultMailbox' => __('Default Mailbox', 'streamery-forms'),
			'defaultMailboxDescription' => __('Set this mailbox as the default for new form submissions.', 'streamery-forms'),
			'default' => __('Default', 'streamery-forms'),
			'createMailboxDescription' => __('Create a new mailbox to receive form submissions.', 'streamery-forms'),
			'updateMailboxDescription' => __('Update the mailbox details below.', 'streamery-forms'),
			'defaultMailboxCannotBeDeleted' => __('Default mailbox cannot be deleted', 'streamery-forms'),
			'deleteMailbox' => __('Delete mailbox', 'streamery-forms'),

			// Settings - Labels
			'labels' => __('Labels', 'streamery-forms'),
			'manageLabels' => __('Manage labels for organizing form entries.', 'streamery-forms'),
			'addLabel' => __('Add Label', 'streamery-forms'),
			'createLabel' => __('Create Label', 'streamery-forms'),
			'editLabel' => __('Edit Label', 'streamery-forms'),
			'labelCreated' => __('Label created', 'streamery-forms'),
			'labelCreatedDesc' => __('The label has been created successfully.', 'streamery-forms'),
			'labelUpdated' => __('Label updated', 'streamery-forms'),
			'labelUpdatedDesc' => __('The label has been updated successfully.', 'streamery-forms'),
			'labelDeleted' => __('Label deleted', 'streamery-forms'),
			'labelDeletedDesc' => __('The label has been deleted successfully.', 'streamery-forms'),
			'confirmDeleteLabel' => __('Are you sure you want to delete this label?', 'streamery-forms'),
			'loadingLabels' => __('Loading labels...', 'streamery-forms'),
			'errorLabels' => __('Error:', 'streamery-forms'),
			'noLabelsFound' => __('No labels found. Create your first label to get started.', 'streamery-forms'),
			'name' => __('Name', 'streamery-forms'),
			'nameRequired' => __('Name is required', 'streamery-forms'),
			'description' => __('Description', 'streamery-forms'),
			'color' => __('Color', 'streamery-forms'),
			'colorInvalid' => __('Color must be a valid hex color (e.g., #FF0000)', 'streamery-forms'),

			// Block Editor - Field Controls
			'globalFieldSettings' => __('Global Field Settings', 'streamery-forms'),
			'useCustomName' => __('Use custom name', 'streamery-forms'),
			'useCustomId' => __('Use custom ID', 'streamery-forms'),
			'placeholder' => __('Placeholder', 'streamery-forms'),
			'required' => __('Required', 'streamery-forms'),
			'fieldValueSettings' => __('Field value', 'streamery-forms'),
			'fieldValueSource' => __('Field', 'streamery-forms'),
			'fieldValuePrefix' => __('Text before', 'streamery-forms'),
			'fieldValueSuffix' => __('Text after', 'streamery-forms'),
			'fieldValueAffixHelp' => __('Only shown together with a value.', 'streamery-forms'),
			'fieldValueFallback' => __('Fallback', 'streamery-forms'),
			'fieldValueFallbackHelp' => __('Shown while the field is empty. Leave empty to hide the block until there is a value.', 'streamery-forms'),
			'fieldValueShowLabels' => __('Show option labels instead of values', 'streamery-forms'),
			'fieldValueBold' => __('Bold value', 'streamery-forms'),
			'fieldValueBoldHelp' => __('Only the value, not the text before or after it.', 'streamery-forms'),
			'fieldValueChooseField' => __('Choose a field in the sidebar', 'streamery-forms'),
			'hideLabel' => __('Hide label', 'streamery-forms'),
			'hideLabelHelp' => __('The label stays readable for screen readers.', 'streamery-forms'),
			'imagePosition' => __('Image position', 'streamery-forms'),
			'imagePositionBefore' => __('Before the text', 'streamery-forms'),
			'imagePositionAfter' => __('After the text', 'streamery-forms'),
			'imagePositionTopLeft' => __('Top left', 'streamery-forms'),
			'imagePositionCenter' => __('Centered (no checkbox)', 'streamery-forms'),
			'allowCustomOption' => __('Allow custom option', 'streamery-forms'),
			'allowCustomOptionHelp' => __('Adds a last option with a text field for the visitor\'s own answer.', 'streamery-forms'),
			'customOptionPlaceholder' => __('Custom option placeholder', 'streamery-forms'),
			'customOptionDefault' => __('Other…', 'streamery-forms'),
			'optionImage' => __('Image', 'streamery-forms'),
			'removeImage' => __('Remove image', 'streamery-forms'),
			'conditionalLogic' => __('Conditional logic', 'streamery-forms'),
			'conditionalWhere' => __('Where', 'streamery-forms'),
			'conditionalShowWhen' => __('Show when field', 'streamery-forms'),
			'conditionalOperator' => __('Condition', 'streamery-forms'),
			'conditionalValue' => __('Value', 'streamery-forms'),
			'conditionalShowNone' => __('— None —', 'streamery-forms'),
			'conditionalOperatorEquals' => __('Equals', 'streamery-forms'),
			'conditionalOperatorNotEquals' => __('Does not equal', 'streamery-forms'),
			'conditionalOperatorIsEmpty' => __('Is empty', 'streamery-forms'),
			'conditionalOperatorIsNotEmpty' => __('Is not empty', 'streamery-forms'),
			'conditionalOperatorContains' => __('Contains', 'streamery-forms'),
			'defaultValueFromField' => __('Default value from field', 'streamery-forms'),
			'defaultValueFromFieldHelp' => __('Use value of this field as preselection', 'streamery-forms'),
			'conditionalAddFilter' => __('Add condition', 'streamery-forms'),
			'conditionalDeleteAll' => __('Delete all', 'streamery-forms'),
			'conditionalLogicAnd' => __('AND', 'streamery-forms'),
			'conditionalLogicOr' => __('OR', 'streamery-forms'),
			'conditionalSelectValue' => __('Select value…', 'streamery-forms'),
			'stepNavigationButtonLabels' => __('Button labels', 'streamery-forms'),
			'stepNavPrevLabel' => __('Previous button', 'streamery-forms'),
			'stepNavPrevLabelHelp' => __('Shown on all steps except the first.', 'streamery-forms'),
			'stepNavNextLabel' => __('Next button', 'streamery-forms'),
			'stepNavNextLabelHelp' => __('Shown when there is a following step.', 'streamery-forms'),
			'stepNavSubmitLabel' => __('Submit button', 'streamery-forms'),
			'stepNavSubmitLabelHelp' => __('Shown on the last visible step (e.g. when using conditional steps).', 'streamery-forms'),
			'enterLabel' => __('Enter label', 'streamery-forms'),
			'enterHelpText' => __('Enter help text', 'streamery-forms'),
			'id' => __('ID', 'streamery-forms'),
			'selectAnOption' => __('Select an option...', 'streamery-forms'),
			'buttonLabel' => __('Button Label', 'streamery-forms'),
			'successModalHiddenInPreview' => __('Success modal (hidden in preview)', 'streamery-forms'),
			'toggleSuccessView' => __('Toggle Success View', 'streamery-forms'),
			'successScreen' => __('Success screen', 'streamery-forms'),
			'successScreenShow' => __('Edit success screen', 'streamery-forms'),
			'successScreenBackToForm' => __('Back to form', 'streamery-forms'),
			'changeTemplate' => __('Change template', 'streamery-forms'),
			'formSettings' => __('Form Settings', 'streamery-forms'),
			'formSettingsStorage' => __('Storage & Inbox', 'streamery-forms'),
			'formSettingsStorageDescription' => __('Every submission of this form is stored in the inbox. Choose where it lands.', 'streamery-forms'),
			'formSettingsProviders' => __('Providers & Actions', 'streamery-forms'),
			'formSettingsProvidersDescription' => __('These run in order every time the form is submitted. Storage always runs first, so a failing integration can never lose a submission.', 'streamery-forms'),
			'formSettingsSpam' => __('Spam Protection', 'streamery-forms'),
			'formSettingsSpamDescription' => __('Rate limiting and submit-timing checks always run and are not configurable per form.', 'streamery-forms'),
			'formSettingsAfterSubmit' => __('After Submit', 'streamery-forms'),
			'formSettingsAfterSubmitDescription' => __('You edit the success screen from the toolbar. Use the fields below for the error message and an optional redirect.', 'streamery-forms'),
			'formSettingsPrivacy' => __('Privacy', 'streamery-forms'),
			'formSettingsPrivacyDescription' => __('Controls what is kept about each submission, and for how long.', 'streamery-forms'),
			'alwaysOn' => __('Always on', 'streamery-forms'),
			'enableProvider' => __('Enable provider', 'streamery-forms'),
			'noOptionalProviders' => __('No additional providers yet. Add them under Streamery Forms → Providers.', 'streamery-forms'),
			'errorMessage' => __('Error message', 'streamery-forms'),
			'errorMessageDefault' => __('Your submission could not be sent. Please try again.', 'streamery-forms'),
			'redirectUrl' => __('Redirect URL', 'streamery-forms'),
			'redirectUrlHelp' => __('If set, the visitor is sent here after a successful submission instead of seeing the success screen.', 'streamery-forms'),
			'redirectUrlInvalid' => __('Enter an absolute URL (https://…) or a path starting with a slash.', 'streamery-forms'),
			'entrySubject' => __('Entry subject', 'streamery-forms'),
			'entrySubjectHelp' => __('Shown as the entry title in the inbox. Placeholders like {form_title} are replaced.', 'streamery-forms'),
			'templateResetWarning' => __('Choosing a new template will replace all current form content. This cannot be undone.', 'streamery-forms'),
			'skin' => __('Skin', 'streamery-forms'),
			'text' => __('Text', 'streamery-forms'),
			'number' => __('Number', 'streamery-forms'),
			'phone' => __('Phone', 'streamery-forms'),
			'url' => __('URL', 'streamery-forms'),
			'search' => __('Search', 'streamery-forms'),
			'enterText' => __('Enter text', 'streamery-forms'),
			'enterEmail' => __('Enter email', 'streamery-forms'),
			'enterPhone' => __('Enter phone number', 'streamery-forms'),
			'enterUrl' => __('Enter URL', 'streamery-forms'),
			'enterNumber' => __('Enter number', 'streamery-forms'),
			'enterSearch' => __('Enter search term', 'streamery-forms'),
			'inputVariationTextDescription' => __('Single-line text input for names, titles, or short answers.', 'streamery-forms'),
			'inputVariationEmailDescription' => __('Email address field with built-in format validation.', 'streamery-forms'),
			'inputVariationPhoneDescription' => __('Phone number field optimized for tel input.', 'streamery-forms'),
			'inputVariationUrlDescription' => __('Website or link field with URL validation.', 'streamery-forms'),
			'inputVariationNumberDescription' => __('Numeric input for quantities, ages, or amounts.', 'streamery-forms'),
			'inputVariationSearchDescription' => __('Search-style input for lookup or filter fields.', 'streamery-forms'),
			'checkboxGroup' => __('Checkboxes', 'streamery-forms'),
			'checkboxVariationGroupDescription' => __('A group of options where visitors can pick several.', 'streamery-forms'),
			/* translators: %d: option number */
			'optionNumber' => __('Option %d', 'streamery-forms'),
			'checkboxVariationConsentDescription' => __('Required privacy or terms consent checkbox.', 'streamery-forms'),
			'checkboxVariationNewsletterDescription' => __('Optional newsletter or marketing opt-in.', 'streamery-forms'),
			'ageGroups' => __('Age Groups', 'streamery-forms'),
			'mr' => __('Mr.', 'streamery-forms'),
			'mrs' => __('Mrs.', 'streamery-forms'),
			'diverse' => __('Diverse', 'streamery-forms'),
			'years017' => __('0-17 years', 'streamery-forms'),
			'years1824' => __('18-24 years', 'streamery-forms'),
			'years2534' => __('25-34 years', 'streamery-forms'),
			'years3544' => __('35-44 years', 'streamery-forms'),
			'years4554' => __('45-54 years', 'streamery-forms'),
			'years5564' => __('55-64 years', 'streamery-forms'),
			'years65Plus' => __('65+ years', 'streamery-forms'),
			'setupYourFirstMailbox' => __('Setup your First Mailbox', 'streamery-forms'),
			'createCustomMailbox' => __('Create a custom mailbox to organize your form entries', 'streamery-forms'),
			'areTheLabelsDefaultOk' => __('Are The Labels (default) ok or change something?', 'streamery-forms'),
			'reviewAndCustomizeLabels' => __('Review and customize your entry labels', 'streamery-forms'),
			'configureEmailProvider' => __('Configure an email provider to receive form submissions', 'streamery-forms'),

			// Block Editor - Select Field
			'selectFieldSettings' => __('Select Field Settings', 'streamery-forms'),
			'populateOptions' => __('Populate options', 'streamery-forms'),
			'populatedOptionsDescription' => __('Options are not managed in the editor. They are filled when the page loads via the streamery-forms/select/populated_options filter in your theme or plugin.', 'streamery-forms'),
			'populatedOptionsExampleLabel' => __('Example', 'streamery-forms'),
			'populatedOptionsExampleCode' => "add_filter(\n  'streamery-forms/select/populated_options',\n  function ( \$options, \$context ) {\n    if ( \$context['name'] === 'country' ) {\n      return array(\n        array( 'label' => 'Germany', 'value' => 'de' ),\n      );\n    }\n    return \$options;\n  },\n  10,\n  2\n);",
			// Block Editor - Checkbox Field
			'checkboxFieldSettings' => __('Checkbox Field Settings', 'streamery-forms'),
			'consent' => __('Consent', 'streamery-forms'),
			'iAgreeToPrivacyPolicy' => __('I agree to the privacy policy.', 'streamery-forms'),
			'newsletter' => __('Newsletter', 'streamery-forms'),
			'subscribeToNewsletter' => __('Subscribe to newsletter', 'streamery-forms'),
			'checkboxStyleDefault' => __('Standard', 'streamery-forms'),
			'checkboxStyleToggle' => __('Schalter', 'streamery-forms'),
			'checkboxStyleCards' => __('Karten', 'streamery-forms'),
			'checkboxStyleBadges' => __('Badges', 'streamery-forms'),
			'style' => __('Style', 'streamery-forms'),
			'addOptionsInSidebar' => __('Add options via sidebar (Checkbox Field Settings).', 'streamery-forms'),
			// Block Editor - Radio Field
			'radioFieldSettings' => __('Radio Field Settings', 'streamery-forms'),
			'radioStyleDefault' => __('Standard', 'streamery-forms'),
			'radioStyleToggle' => __('Schalter', 'streamery-forms'),
			'radioStyleBadges' => __('Badges', 'streamery-forms'),
			'radioStyleCards' => __('Karten', 'streamery-forms'),
			'layout' => __('Layout', 'streamery-forms'),
			'horizontal' => __('Horizontal', 'streamery-forms'),
			'vertical' => __('Vertical', 'streamery-forms'),
			// Block Editor - Date/Time Field
			'dateTimeFieldSettings' => __('Date / Time Field Settings', 'streamery-forms'),
			'date' => __('Date', 'streamery-forms'),
			'time' => __('Time', 'streamery-forms'),
			'dateTime' => __('Date & Time', 'streamery-forms'),
			'single' => __('Single', 'streamery-forms'),
			'range' => __('Range', 'streamery-forms'),
			'mode' => __('Mode', 'streamery-forms'),
			// Block Editor - Slider Field
			'sliderFieldSettings' => __('Slider Field Settings', 'streamery-forms'),
			'sliderDisplayOptions' => __('Slider display', 'streamery-forms'),
			'min' => __('Min', 'streamery-forms'),
			'max' => __('Max', 'streamery-forms'),
			'step' => __('Step', 'streamery-forms'),
			'orientation' => __('Orientation', 'streamery-forms'),
			'orientationHorizontal' => __('Horizontal', 'streamery-forms'),
			'orientationVertical' => __('Vertical', 'streamery-forms'),
			'direction' => __('Direction', 'streamery-forms'),
			'directionLtr' => __('Left to right', 'streamery-forms'),
			'directionRtl' => __('Right to left', 'streamery-forms'),
			'tooltips' => __('Show tooltips', 'streamery-forms'),
			'connectHandles' => __('Connect handles (range)', 'streamery-forms'),
			'margin' => __('Min. distance between handles', 'streamery-forms'),
			'limit' => __('Max. distance between handles', 'streamery-forms'),
			'paddingStart' => __('Padding start', 'streamery-forms'),
			'paddingEnd' => __('Padding end', 'streamery-forms'),
			'animate' => __('Animate on set', 'streamery-forms'),
			'animationDuration' => __('Animation duration (ms)', 'streamery-forms'),
			'defaultValue' => __('Default value', 'streamery-forms'),
			'noDefaultValue' => __('No default', 'streamery-forms'),
			'defaultValueHelp' => __('Prefilled in the field. Visitors can change it.', 'streamery-forms'),
			'defaultValueStart' => __('Default value (start)', 'streamery-forms'),
			'defaultValueEnd' => __('Default value (end)', 'streamery-forms'),
			'basicForm' => __('Basic Form', 'streamery-forms'),
			'templateCategoryStart' => __('Start', 'streamery-forms'),
			'templateCategoryBasics' => __('Basics', 'streamery-forms'),
			'templateCategoryAdvanced' => __('Advanced', 'streamery-forms'),
			'templateCategoryMultiStep' => __('Multi-step', 'streamery-forms'),
			'templateSelectIntro' => __('Choose a template to get started. You can adjust the fields afterwards.', 'streamery-forms'),
			'templateBlank' => __('Blank', 'streamery-forms'),
			'templateContact' => __('Contact Form', 'streamery-forms'),
			'templateNewsletter' => __('Newsletter Signup', 'streamery-forms'),
			'templateCallback' => __('Callback Request', 'streamery-forms'),
			'templateEventRsvp' => __('Event Registration / RSVP', 'streamery-forms'),
			'templateJobApplication' => __('Job Application', 'streamery-forms'),
			'templateFeedback' => __('Customer Feedback / Survey', 'streamery-forms'),
			'templateBasicMultiStep' => __('Basic Multi-Step Form', 'streamery-forms'),
			'templateProjectRequest' => __('Project Request (Multi-Step)', 'streamery-forms'),
			'stepTitlePersonalData' => __('Personal data', 'streamery-forms'),
			'stepTitleMessage' => __('Message', 'streamery-forms'),
			'templateSupportTicket' => __('Support Ticket', 'streamery-forms'),
			'templateTableReservation' => __('Table Reservation', 'streamery-forms'),
			'templateProductConfigurator' => __('Product Configurator', 'streamery-forms'),
			// Template field labels (for form templates)
			'firstName' => __('First name', 'streamery-forms'),
			'lastName' => __('Last name', 'streamery-forms'),
			'subject' => __('Subject', 'streamery-forms'),
			'message' => __('Message', 'streamery-forms'),
			'privacyConsent' => __('Privacy consent', 'streamery-forms'),
			'iAgreeToPrivacy' => __('I agree to the privacy policy', 'streamery-forms'),
			'newsletterFirstNameHelp' => __('So we can address you personally', 'streamery-forms'),
			'bestReachability' => __('Best time to reach', 'streamery-forms'),
			'reasonForCall' => __('Reason for call (optional)', 'streamery-forms'),
			'morning' => __('Morning', 'streamery-forms'),
			'afternoon' => __('Afternoon', 'streamery-forms'),
			'evening' => __('Evening', 'streamery-forms'),
			'numberOfGuests' => __('Number of guests', 'streamery-forms'),
			'dietaryPreferences' => __('Dietary preferences', 'streamery-forms'),
			'vegetarian' => __('Vegetarian', 'streamery-forms'),
			'vegan' => __('Vegan', 'streamery-forms'),
			'allergies' => __('Allergies', 'streamery-forms'),
			'eveningEventParticipation' => __('Evening event participation', 'streamery-forms'),
			'address' => __('Address', 'streamery-forms'),
			'desiredPosition' => __('Desired position', 'streamery-forms'),
			'developer' => __('Developer', 'streamery-forms'),
			'designer' => __('Designer', 'streamery-forms'),
			'marketing' => __('Marketing', 'streamery-forms'),
			'earliestStartDate' => __('Earliest start date', 'streamery-forms'),
			'salaryExpectation' => __('Salary expectation', 'streamery-forms'),
			'resumeCv' => __('Resume / CV (PDF)', 'streamery-forms'),
			'coverLetter' => __('Cover letter / Portfolio', 'streamery-forms'),
			'howSatisfied' => __('How satisfied were you? (1-10)', 'streamery-forms'),
			'whatDidYouLike' => __('What did you particularly like?', 'streamery-forms'),
			'whatCanWeImprove' => __('What can we improve?', 'streamery-forms'),
			'contactForFollowUp' => __('May we contact you for follow-up questions?', 'streamery-forms'),
			'emailFollowUp' => __('Email (for follow-up)', 'streamery-forms'),
			'theProject' => __('The project', 'streamery-forms'),
			'projectType' => __('Project type', 'streamery-forms'),
			'currentStatus' => __('Current status', 'streamery-forms'),
			'justAnIdea' => __('Just an idea', 'streamery-forms'),
			'specificationAvailable' => __('Specification available', 'streamery-forms'),
			'relaunch' => __('Relaunch', 'streamery-forms'),
			'framework' => __('Framework', 'streamery-forms'),
			'budgetRange' => __('Budget range', 'streamery-forms'),
			'deadline' => __('Deadline', 'streamery-forms'),
			'contactDetails' => __('Contact details', 'streamery-forms'),
			'company' => __('Company', 'streamery-forms'),
			'customerIdOrderNumber' => __('Customer ID / Order number', 'streamery-forms'),
			'problemCategory' => __('Problem category', 'streamery-forms'),
			'technical' => __('Technical', 'streamery-forms'),
			'billing' => __('Billing', 'streamery-forms'),
			'shipping' => __('Shipping', 'streamery-forms'),
			'urgency' => __('Urgency', 'streamery-forms'),
			'low' => __('Low', 'streamery-forms'),
			'medium' => __('Medium', 'streamery-forms'),
			'critical' => __('Critical', 'streamery-forms'),
			'problemDescription' => __('Problem description', 'streamery-forms'),
			'screenshotUpload' => __('Screenshot', 'streamery-forms'),
			'date' => __('Date', 'streamery-forms'),
			'time' => __('Time', 'streamery-forms'),
			'area' => __('Area', 'streamery-forms'),
			'indoors' => __('Indoors', 'streamery-forms'),
			'terrace' => __('Terrace', 'streamery-forms'),
			'specialOccasions' => __('Special occasions (e.g. birthday)', 'streamery-forms'),
			'productChoice' => __('Product choice', 'streamery-forms'),
			'basicPackage' => __('Basic package – 99 €', 'streamery-forms'),
			'premiumPackage' => __('Premium – 199 €', 'streamery-forms'),
			'addOns' => __('Add-ons', 'streamery-forms'),
			'expressProcessing' => __('Express processing +20 €', 'streamery-forms'),
			'giftWrapping' => __('Gift wrapping +5 €', 'streamery-forms'),
			'deliveryAddress' => __('Delivery address', 'streamery-forms'),
			'billingAddressSame' => __('Billing address', 'streamery-forms'),
			'sameAsDelivery' => __('Same as delivery address', 'streamery-forms'),
			'generalEnquiry' => __('General enquiry', 'streamery-forms'),
			'support' => __('Support', 'streamery-forms'),
			'other' => __('Other', 'streamery-forms'),
			'country' => __('Country', 'streamery-forms'),
			'federalStates' => __('Federal States', 'streamery-forms'),
			'germany' => __('Germany', 'streamery-forms'),
			'austria' => __('Austria', 'streamery-forms'),
			'switzerland' => __('Switzerland', 'streamery-forms'),
			'france' => __('France', 'streamery-forms'),
			'italy' => __('Italy', 'streamery-forms'),
			'spain' => __('Spain', 'streamery-forms'),
			'netherlands' => __('Netherlands', 'streamery-forms'),
			'belgium' => __('Belgium', 'streamery-forms'),
			'poland' => __('Poland', 'streamery-forms'),
			'czechRepublic' => __('Czech Republic', 'streamery-forms'),
			'badenWurttemberg' => __('Baden-Württemberg', 'streamery-forms'),
			'bavaria' => __('Bavaria', 'streamery-forms'),
			'berlin' => __('Berlin', 'streamery-forms'),
			'brandenburg' => __('Brandenburg', 'streamery-forms'),
			'bremen' => __('Bremen', 'streamery-forms'),
			'hamburg' => __('Hamburg', 'streamery-forms'),
			'hesse' => __('Hesse', 'streamery-forms'),
			'mecklenburgWesternPomerania' => __('Mecklenburg-Western Pomerania', 'streamery-forms'),
			'lowerSaxony' => __('Lower Saxony', 'streamery-forms'),
			'northRhineWestphalia' => __('North Rhine-Westphalia', 'streamery-forms'),
			'rhinelandPalatinate' => __('Rhineland-Palatinate', 'streamery-forms'),
			'saarland' => __('Saarland', 'streamery-forms'),
			'saxony' => __('Saxony', 'streamery-forms'),
			'saxonyAnhalt' => __('Saxony-Anhalt', 'streamery-forms'),
			'schleswigHolstein' => __('Schleswig-Holstein', 'streamery-forms'),
			'thuringia' => __('Thuringia', 'streamery-forms'),

			// Dashboard
			'dashboard' => __('Dashboard', 'streamery-forms'),
			'overview' => __('Overview', 'streamery-forms'),
			'analytics' => __('Analytics', 'streamery-forms'),
			'reports' => __('Reports', 'streamery-forms'),
			'notifications' => __('Notifications', 'streamery-forms'),
			'totalRevenue' => __('Total Revenue', 'streamery-forms'),
			'subscriptions' => __('Subscriptions', 'streamery-forms'),
			'sales' => __('Sales', 'streamery-forms'),
			'activeNow' => __('Active Now', 'streamery-forms'),
			'download' => __('Download', 'streamery-forms'),
			'recentSales' => __('Recent Sales', 'streamery-forms'),
			'youMadeSalesThisMonth' => __('You made 265 sales this month.', 'streamery-forms'),
			'fromLastMonth' => __('from last month', 'streamery-forms'),
			'sinceLastHour' => __('since last hour', 'streamery-forms'),

			// Inbox
			'junk' => __('Junk', 'streamery-forms'),
			'archive' => __('Archive', 'streamery-forms'),
			'trash' => __('Trash', 'streamery-forms'),
			'noData' => __('No data', 'streamery-forms'),
			'entryLabels' => __('Entry Labels', 'streamery-forms'),

			// Inbox Folders
			'inboxFolders' => __('Folders', 'streamery-forms'),
			'newFolder' => __('New Folder', 'streamery-forms'),
			'editFolder' => __('Edit Folder', 'streamery-forms'),
			'deleteFolder' => __('Delete Folder', 'streamery-forms'),
			'folderName' => __('Folder name', 'streamery-forms'),
			'folderCreated' => __('Folder created', 'streamery-forms'),
			'folderUpdated' => __('Folder updated', 'streamery-forms'),
			'folderDeleted' => __('Folder deleted', 'streamery-forms'),
			'confirmDeleteFolder' => __('Are you sure you want to delete this folder? Entries will be removed from the folder but not deleted.', 'streamery-forms'),
			'createSubfolder' => __('Create Subfolder', 'streamery-forms'),
			'renameFolder' => __('Rename Folder', 'streamery-forms'),

			// Providers - Additional strings
			'providerTypeRequired' => __('Provider type is required', 'streamery-forms'),
			'select' => __('Select', 'streamery-forms'),
			'myEmailProvider' => __('My Email Provider', 'streamery-forms'),
			'providerNameDescription' => __('A descriptive name for this provider.', 'streamery-forms'),
			'selectProviderType' => __('Select a provider type', 'streamery-forms'),
			'selectProviderTypeDescription' => __('Select the type of provider.', 'streamery-forms'),
			'formIdentifierOptional' => __('Form Identifier (optional)', 'streamery-forms'),
			'leaveEmptyForGlobalProvider' => __('Leave empty for global provider', 'streamery-forms'),
			'formIdentifierDescription' => __('Form-specific provider. Leave empty for global provider that can be used by all forms.', 'streamery-forms'),
			'enableOrDisableProvider' => __('Enable or disable this provider.', 'streamery-forms'),
			'manageProvidersDescription' => __('Manage form submission providers (Email, Webhook, etc.).', 'streamery-forms'),
			'updateProviderDetails' => __('Update the provider details below.', 'streamery-forms'),
			'configureNewProvider' => __('Configure a new provider for form submissions.', 'streamery-forms'),
			'type' => __('Type:', 'streamery-forms'),
			'form' => __('Form:', 'streamery-forms'),
			'globalProvider' => __('Global Provider', 'streamery-forms'),
			'selectProviders' => __('Select providers', 'streamery-forms'),
			'editTemplate' => __('Edit template', 'streamery-forms'),
			'useProviderLayout' => __('Use provider layout', 'streamery-forms'),
			'useProviderLayoutHelp' => __('When enabled, your content replaces the {content} placeholder in the provider template. When disabled, this HTML is used as the full email body.', 'streamery-forms'),
			'contentPlaceholder' => __('Content (replaces {content})', 'streamery-forms'),
			'fullEmailBody' => __('Full email body (HTML)', 'streamery-forms'),
			'availablePlaceholders' => __('Available placeholders', 'streamery-forms'),
			'providerOnlyWhen' => __('Provider only when', 'streamery-forms'),
			'insertedPlaceholders' => __('Inserted placeholders', 'streamery-forms'),
			'replace' => __('Replace', 'streamery-forms'),
			'remove' => __('Remove', 'streamery-forms'),

			// Labels - Additional strings
			'manageLabelsDescription' => __('Manage labels for organizing and categorizing form entries.', 'streamery-forms'),
			'updateLabelDetails' => __('Update the label details below.', 'streamery-forms'),
			'createNewLabel' => __('Create a new label to organize your form entries.', 'streamery-forms'),
			'important' => __('Important', 'streamery-forms'),
			'uniqueNameForLabel' => __('A unique name for this label.', 'streamery-forms'),
			'optionalDescriptionForLabel' => __('Optional description for this label', 'streamery-forms'),
			'optionalDescriptionHelp' => __('An optional description to help identify this label.', 'streamery-forms'),
			'chooseColorForLabel' => __('Choose a color to visually identify this label.', 'streamery-forms'),

			// Welcome Page - Additional strings
			'letsGetYouStarted' => __("Let's get you started with a few quick steps", 'streamery-forms'),
			'allSetRedirecting' => __('🎉 All set! Redirecting to inbox...', 'streamery-forms'),

			// Application Layout
			'pluginName' => __('Streamery Forms', 'streamery-forms'),
			'toggleNavigationMenu' => __('Toggle navigation menu', 'streamery-forms'),
			'toggleUserMenu' => __('Toggle user menu', 'streamery-forms'),
			'myAccount' => __('My Account', 'streamery-forms'),
			'settings' => __('Settings', 'streamery-forms'),
			'support' => __('Support', 'streamery-forms'),
			'logout' => __('Logout', 'streamery-forms'),
			'charts' => __('Charts', 'streamery-forms'),

			// Options Modal
			'manageOptions' => __('Manage Options', 'streamery-forms'),
			'syncLabelAndValue' => __('Sync label and value', 'streamery-forms'),
			'addBulkOptions' => __('Add Bulk Options', 'streamery-forms'),
			'bulkOptionsPlaceholder' => __('Enter options separated by commas. Use format: Label or Label:value', 'streamery-forms'),
			'bulkOptionsExample' => __('Example: Red,Blue,Green or Red:red,Blue:blue,Green:green', 'streamery-forms'),
			'addOptions' => __('Add Options', 'streamery-forms'),
			'move' => __('Move', 'streamery-forms'),
			'label' => __('Label', 'streamery-forms'),
			'value' => __('Value', 'streamery-forms'),
			'actions' => __('Actions', 'streamery-forms'),
			'newLabel' => __('New label...', 'streamery-forms'),
			'newValue' => __('New value...', 'streamery-forms'),
			'add' => __('Add', 'streamery-forms'),
			'selected' => __('selected', 'streamery-forms'),
			'deleteSelected' => __('Delete Selected', 'streamery-forms'),
			'chooseTemplateOrStartEmpty' => __('Choose a template or start empty', 'streamery-forms'),
			'startWithoutTemplate' => __('Start without template', 'streamery-forms'),
			'options' => __('Options:', 'streamery-forms'),

			// File Upload Field
			'fileUploadSettings' => __('File Upload Settings', 'streamery-forms'),
			'allowMultipleFiles' => __('Allow multiple files', 'streamery-forms'),
			'maxFiles' => __('Maximum number of files', 'streamery-forms'),
			'acceptedFileTypes' => __('Accepted file types', 'streamery-forms'),
			'acceptTypesHelp' => __('Comma-separated MIME types or file extensions (e.g., image/*,application/pdf,.doc,.docx)', 'streamery-forms'),
			'maxFileSize' => __('Maximum file size (MB)', 'streamery-forms'),
			/* translators: %s: maximum upload size in megabytes. */
			'maxFileSizeHint' => __('Maximum: %s MB (WordPress upload limit)', 'streamery-forms'),
			'maxFileSizeHintDefault' => __('Maximum file size is limited by WordPress upload settings', 'streamery-forms'),
			'allowUrlUpload' => __('Allow URL upload', 'streamery-forms'),
			'allowUrlUploadHelp' => __('Allow users to upload files by providing a URL', 'streamery-forms'),
			'selectCsvFileToUpload' => __('Select a file to upload', 'streamery-forms'),
			'orDragAndDrop' => __('or drag and drop it here', 'streamery-forms'),
			'orUploadFromUrl' => __('Or upload from URL', 'streamery-forms'),
			'addFileUrl' => __('Add file URL', 'streamery-forms'),
			'uploadingFile' => __('Uploading file...', 'streamery-forms'),
			'uploadFailed' => __('Upload failed', 'streamery-forms'),
			'fileTooLarge' => __('File is too large', 'streamery-forms'),
			'invalidFileType' => __('Invalid file type', 'streamery-forms'),
			'maxFilesReached' => __('Maximum number of files reached', 'streamery-forms'),
			'removeFile' => __('Remove file', 'streamery-forms'),
			'cancel' => __('Cancel', 'streamery-forms'),
			'download' => __('Download', 'streamery-forms'),
			'viewFile' => __('View file', 'streamery-forms'),

			// SMTP Settings
			'smtpSettings' => __('SMTP Settings', 'streamery-forms'),
			'smtpSettingsDescription' => __('Configure SMTP settings for sending emails via wp_mail().', 'streamery-forms'),
			'smtpPageHint' => __('To configure SMTP and send form submission emails reliably, please activate the WP Mail SMTP plugin.', 'streamery-forms'),
			'wpMailSmtpHint' => __('WP Mail SMTP plugin', 'streamery-forms'),
			'wpMailLoggingHint' => __('For email logging and debugging, you can also use the', 'streamery-forms'),
			'wpMailLoggingPlugin' => __('WP Mail Logging plugin', 'streamery-forms'),
			'smtpAdvancedSettings' => __('For advanced SMTP features like email logging, conditional routing, and multiple providers, consider using the', 'streamery-forms'),
			'wpMailSmtpPlugin' => __('WP Mail SMTP plugin', 'streamery-forms'),
			'smtpConfiguration' => __('SMTP Configuration', 'streamery-forms'),
			'smtpConfigurationDescription' => __('Configure your SMTP server settings to send emails reliably.', 'streamery-forms'),
			'enableSmtp' => __('Enable SMTP', 'streamery-forms'),
			'enableSmtpDescription' => __('Enable SMTP to send emails through a custom SMTP server.', 'streamery-forms'),
			'smtpHost' => __('SMTP Host', 'streamery-forms'),
			'smtpHostRequired' => __('SMTP host is required', 'streamery-forms'),
			'smtpHostDescription' => __('The SMTP server hostname (e.g., smtp.gmail.com).', 'streamery-forms'),
			'smtpPort' => __('SMTP Port', 'streamery-forms'),
			'smtpPortRequired' => __('SMTP port is required', 'streamery-forms'),
			'smtpPortDescription' => __('The SMTP server port (usually 587 for TLS, 465 for SSL).', 'streamery-forms'),
			'smtpEncryption' => __('Encryption', 'streamery-forms'),
			'smtpEncryptionDescription' => __('Choose the encryption method for your SMTP connection.', 'streamery-forms'),
			'selectEncryption' => __('Select encryption', 'streamery-forms'),
			'smtpAuth' => __('SMTP Authentication', 'streamery-forms'),
			'smtpAuthDescription' => __('Enable if your SMTP server requires authentication.', 'streamery-forms'),
			'smtpUsername' => __('SMTP Username', 'streamery-forms'),
			'smtpUsernameRequired' => __('SMTP username is required when authentication is enabled', 'streamery-forms'),
			'smtpUsernameDescription' => __('Your SMTP username (usually your email address).', 'streamery-forms'),
			'smtpPassword' => __('SMTP Password', 'streamery-forms'),
			'smtpPasswordPlaceholder' => __('Leave blank to keep current password', 'streamery-forms'),
			'smtpPasswordDescription' => __('Your SMTP password. Leave blank to keep the current password.', 'streamery-forms'),
			'smtpFromSettings' => __('From Email Settings', 'streamery-forms'),
			'smtpFromEmail' => __('From Email', 'streamery-forms'),
			'smtpFromEmailDescription' => __('The email address that will appear as the sender.', 'streamery-forms'),
			'smtpFromName' => __('From Name', 'streamery-forms'),
			'smtpFromNamePlaceholder' => __('Your Site Name', 'streamery-forms'),
			'smtpFromNameDescription' => __('The name that will appear as the sender.', 'streamery-forms'),
			'testConnection' => __('Test Connection', 'streamery-forms'),
			'testing' => __('Testing...', 'streamery-forms'),
			'saving' => __('Saving...', 'streamery-forms'),
			'smtpSettingsSaved' => __('SMTP settings have been saved successfully.', 'streamery-forms'),
			'smtpTestSuccess' => __('Test Email Sent', 'streamery-forms'),
			'smtpTestFailed' => __('Test Failed', 'streamery-forms'),
			'smtpTestFailedDesc' => __('Failed to send test email. Please check your SMTP settings.', 'streamery-forms'),
			'smtpNotEnabled' => __('SMTP is not enabled. Please enable SMTP before testing.', 'streamery-forms'),
			'invalidEmail' => __('Invalid email address', 'streamery-forms'),
			'testSMTPConnection' => __('Test SMTP Connection', 'streamery-forms'),
			'testSMTPConnectionDescription' => __('Test your SMTP settings by sending a test email.', 'streamery-forms'),
			'validatingSettings' => __('Validating Settings', 'streamery-forms'),
			'configuringSMTP' => __('Configuring SMTP', 'streamery-forms'),
			'connectingToServer' => __('Connecting to Server', 'streamery-forms'),
			'authenticating' => __('Authenticating', 'streamery-forms'),
			'sendingTestEmail' => __('Sending Test Email', 'streamery-forms'),
			'receivingResponse' => __('Receiving Response', 'streamery-forms'),
			'settingsValid' => __('Settings are valid', 'streamery-forms'),
			'connectedToServer' => __('Connected to server', 'streamery-forms'),
			'authenticationSuccessful' => __('Authentication successful', 'streamery-forms'),
			'authenticationNotRequired' => __('Authentication not required', 'streamery-forms'),
			'testEmailSent' => __('Test email sent', 'streamery-forms'),
			'errorReceived' => __('Error received', 'streamery-forms'),
			'testProgress' => __('Test Progress', 'streamery-forms'),
			'testSuccessful' => __('Test Successful', 'streamery-forms'),
			'testFailed' => __('Test Failed', 'streamery-forms'),
			'logs' => __('Logs', 'streamery-forms'),
			'startTest' => __('Start Test', 'streamery-forms'),
			'smtpSettings' => __('SMTP Settings', 'streamery-forms'),
			'from' => __('From', 'streamery-forms'),
			'errorDetails' => __('Error Details', 'streamery-forms'),
			'testEmailAddress' => __('Test Email Address', 'streamery-forms'),
			'testEmailPlaceholder' => __('Enter email address to receive test email', 'streamery-forms'),
			'testEmailDescription' => __('The email address where the test email will be sent.', 'streamery-forms'),

			// Email Logging
			'enableEmailLogging' => __('Enable Email Logging', 'streamery-forms'),
			'enableEmailLoggingDescription' => __('Log all emails sent through wp_mail() for debugging and auditing purposes.', 'streamery-forms'),
			'emailLogs' => __('Email Logs', 'streamery-forms'),
			'emailLogsDescription' => __('View and manage all logged emails.', 'streamery-forms'),
			'noEmailLogsFound' => __('No email logs found.', 'streamery-forms'),
			'emailLogDeleted' => __('Email log deleted', 'streamery-forms'),
			'emailLogDeletedDesc' => __('The email log has been deleted successfully.', 'streamery-forms'),
			'confirmDeleteAllEmailLogs' => __('Are you sure you want to delete all email logs?', 'streamery-forms'),
			'allEmailLogsDeleted' => __('All email logs deleted', 'streamery-forms'),
			'allEmailLogsDeletedDesc' => __('All email logs have been deleted successfully.', 'streamery-forms'),
			'from' => __('From', 'streamery-forms'),
			'date' => __('Date', 'streamery-forms'),
			'showing' => __('Showing', 'streamery-forms'),
			'of' => __('of', 'streamery-forms'),
			'previous' => __('Previous', 'streamery-forms'),
			'next' => __('Next', 'streamery-forms'),
			'deleteAll' => __('Delete All', 'streamery-forms'),

			// Email Templates
			'emailTemplate' => __('Email Template', 'streamery-forms'),
			'emailTemplateDescription' => __('Choose and customize an email template for your notifications.', 'streamery-forms'),
			'selectTemplate' => __('Select Template', 'streamery-forms'),
			'primaryColor' => __('Primary Color', 'streamery-forms'),
			'secondaryColor' => __('Secondary Color', 'streamery-forms'),
			'fontFamily' => __('Font Family', 'streamery-forms'),
			'logoUrl' => __('Logo URL', 'streamery-forms'),
			'logoUrlDescription' => __('URL to your logo image. Will be displayed in the email header.', 'streamery-forms'),
			'selectTemplateToPreview' => __('Select a template to preview', 'streamery-forms'),
			'applyTemplate' => __('Apply Template', 'streamery-forms'),
			'showPreview' => __('Show Preview', 'streamery-forms'),
			'hidePreview' => __('Hide Preview', 'streamery-forms'),

			// Primary Mail
			'primaryMail' => __('Primary Mail', 'streamery-forms'),
			'primaryMailDescription' => __('Mark this email field as the primary email address for form submissions. Only one field per form can be primary.', 'streamery-forms'),
			'primaryMailWarning' => __('Another email field is already set as primary mail. Unset it first or it will be automatically unset when you enable this one.', 'streamery-forms'),

			// Placeholder Input
			'insertPlaceholder' => __('Insert Placeholder', 'streamery-forms'),
			'usePlaceholder' => __('Use Placeholder', 'streamery-forms'),
			'selectPlaceholder' => __('Select Placeholder', 'streamery-forms'),

			// Email Template
			'custom' => __('Custom', 'streamery-forms'),
			'selectEmailTemplateDescription' => __('Select a template or use custom HTML.', 'streamery-forms'),
			'failedToLoadTemplate' => __('Failed to load template.', 'streamery-forms'),
			'templateCustomization' => __('Template Customization', 'streamery-forms'),

			// Email Template Editor
			'emailTemplateEditor' => __('Email Template Editor', 'streamery-forms'),
			'emailTemplateEditorDescription' => __('Edit your email template HTML with live preview', 'streamery-forms'),
			'blank' => __('Blank', 'streamery-forms'),
			'templateSettings' => __('Template Settings', 'streamery-forms'),
			'htmlEditor' => __('HTML Editor', 'streamery-forms'),
			'noPreviewAvailable' => __('No preview available', 'streamery-forms'),
			'save' => __('Save', 'streamery-forms'),
			'edit' => __('Edit', 'streamery-forms'),
			'selectFromMediaLibrary' => __('Select from Media Library', 'streamery-forms'),
			'selectImage' => __('Select Image', 'streamery-forms'),
			'useThisImage' => __('Use this image', 'streamery-forms'),
			'siteName' => __('Site Name', 'streamery-forms'),
			'availablePlaceholders' => __('Available Placeholders', 'streamery-forms'),
			'dragPlaceholderToInsert' => __('Drag and drop or click to insert placeholders', 'streamery-forms'),
			'searchPlaceholders' => __('Search placeholders...', 'streamery-forms'),
			'systemPlaceholders' => __('System', 'streamery-forms'),
			'templatePlaceholders' => __('Template', 'streamery-forms'),
			'formFields' => __('Form Fields', 'streamery-forms'),
			'otherPlaceholders' => __('Other', 'streamery-forms'),

			// Provider Field Validation
			'missingFields' => __('Missing Fields', 'streamery-forms'),
			'missingFieldsDescription' => __('The following fields are referenced in the provider but not present in the form:', 'streamery-forms'),
			'addMissingFields' => __('Add Missing Fields', 'streamery-forms'),

			// Admin Bar
			'adminBarMenu' => __('Admin Bar Menu', 'streamery-forms'),
			'adminBarMenuDescription' => __('Show Streamery Forms in the WordPress admin bar with an unread entries count.', 'streamery-forms'),
			'adminBarMenuEnabled' => __('Admin bar menu has been enabled.', 'streamery-forms'),
			'adminBarMenuDisabled' => __('Admin bar menu has been disabled.', 'streamery-forms'),

			// Custom Fields
			'customFields' => __('Custom Fields', 'streamery-forms'),
			'addCustomField' => __('Add Custom Field', 'streamery-forms'),
			'fieldLabel' => __('Field Label', 'streamery-forms'),
			'fieldNamePreview' => __('Field Name', 'streamery-forms'),
			'dragToInsert' => __('Drag to insert', 'streamery-forms'),

			// Multi-Step Form
			'step' => __('Step', 'streamery-forms'),
			'addStep' => __('Add Step', 'streamery-forms'),
			'deleteStep' => __('Delete Step', 'streamery-forms'),
			'moveLeft' => __('Move Left', 'streamery-forms'),
			'moveRight' => __('Move Right', 'streamery-forms'),
			'stepNavigation' => __('Step Navigation', 'streamery-forms'),
			'back' => __('Back', 'streamery-forms'),
			'submit' => __('Submit', 'streamery-forms'),
			'saveAndContinueLater' => __('Save & Continue Later', 'streamery-forms'),
			'progressSaved' => __('Progress saved', 'streamery-forms'),
			'progressRestored' => __('Progress restored', 'streamery-forms'),
			'progressSettings' => __('Progress Settings', 'streamery-forms'),
			'progressVariant' => __('Display Variant', 'streamery-forms'),
			'progressBar' => __('Progress Bar', 'streamery-forms'),
			'progressBubbles' => __('Step Bubbles', 'streamery-forms'),
			'stepTitle' => __('Step Title', 'streamery-forms'),

			// Support
			'supportStreameryForms' => __('Support Streamery Forms', 'streamery-forms'),
			'supportText' => __('Streamery Forms is free, with no pro version and no locked features. If it saves you time, a coffee helps keep it maintained.', 'streamery-forms'),
			/* translators: %d: submission milestone, e.g. 50. */
			'supportMilestoneTitle' => __('%d+ submissions collected', 'streamery-forms'),
			'supportMilestoneText' => __('Glad Streamery Forms is working for you. If you like it, a coffee or a quick review helps a lot.', 'streamery-forms'),
			'supportOnKofi' => __('Buy a coffee', 'streamery-forms'),
			'sponsorOnGithub' => __('Sponsor on GitHub', 'streamery-forms'),
			'leaveReview' => __('Leave a review', 'streamery-forms'),
			'dismissSupport' => __('Don\'t show again', 'streamery-forms'),
		);
	}
}
