export const allowedBlocks = [
	'streamery-forms/input',
	'streamery-forms/textarea',
	'streamery-forms/select',
	'streamery-forms/checkbox',
	'streamery-forms/radio',
	'streamery-forms/date-time',
	'streamery-forms/slider',
	'streamery-forms/file',
	'streamery-forms/captcha',
	'streamery-forms/honeypot',
	'streamery-forms/step-navigation',
	'streamery-forms/save-progress',
	'core/columns',
	'core/column',
	'core/heading',
	'core/paragraph',
	'core/image',
	'core/list',
	'core/list-item',
	'core/quote',
	'core/table',
	'core/video',
	'core/embed',
	'core/group',
];

export const prioritizedInserterBlocks = allowedBlocks.filter(block => block.startsWith('streamery-forms/'));
